name: vint
on: [push]
jobs:
  vint:
    name: vint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v2
      - name: pip
        run: pip install vim-vint
      - name: lint
        run: vint .
